import {
  bigint,
  index,
  integer,
  numeric,
  pgEnum,
  pgTable,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { seasonMemberships } from './identity';
import { selections } from './sports';
import { currency } from './currency';

export const betType = pgEnum('bet_type', ['SINGLE', 'PARLAY']);
export const betStatus = pgEnum('bet_status', ['PENDING', 'WON', 'LOST', 'PUSHED', 'VOIDED']);

export type BetType = (typeof betType.enumValues)[number];
export type BetStatus = (typeof betStatus.enumValues)[number];

/**
 * `settlementAttempts` increments on every settlement or re-settlement and feeds the
 * settlement idempotency key, so a correction can never collide with the original payout.
 *
 * `clientRequestId` is generated by the client and stable across retries of the same
 * submission — the unique index on it is what makes a double-tapped placement a no-op
 * rather than a second bet.
 */
export const bets = pgTable(
  'bets',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    membershipId: uuid('membership_id')
      .notNull()
      .references(() => seasonMemberships.id),
    type: betType('type').notNull(),
    currency: currency('currency').notNull().default('CASH'),
    stakeCents: bigint('stake_cents', { mode: 'bigint' }).notNull(),
    potentialPayoutCents: bigint('potential_payout_cents', { mode: 'bigint' }).notNull(),
    combinedPriceAmerican: integer('combined_price_american').notNull(),
    status: betStatus('status').notNull().default('PENDING'),
    settlementAttempts: integer('settlement_attempts').notNull().default(0),
    clientRequestId: uuid('client_request_id').notNull(),
    placedAt: timestamp('placed_at', { withTimezone: true }).notNull().defaultNow(),
    settledAt: timestamp('settled_at', { withTimezone: true }),
  },
  (t) => [
    uniqueIndex('bets_client_request_idx').on(t.clientRequestId),
    // Powers both the settlement sweep and Plan 3's My Bets screen.
    index('bets_membership_status_idx').on(t.membershipId, t.status),
  ],
);

/**
 * Legs freeze the line and price they were placed at. Later line movement must never
 * retroactively change a placed bet, so settlement grades from these columns and never
 * from the live `selections` row.
 */
export const betLegs = pgTable(
  'bet_legs',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    betId: uuid('bet_id')
      .notNull()
      .references(() => bets.id),
    selectionId: uuid('selection_id')
      .notNull()
      .references(() => selections.id),
    lineAtPlacement: numeric('line_at_placement', { precision: 5, scale: 2 }),
    priceAtPlacement: integer('price_at_placement').notNull(),
    status: betStatus('status').notNull().default('PENDING'),
    settledAt: timestamp('settled_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('bet_legs_bet_idx').on(t.betId),
    index('bet_legs_selection_idx').on(t.selectionId),
    // The settlement sweep scans for pending legs every ten minutes forever; the partial
    // index keeps that query off the settled bulk of the table.
    index('bet_legs_pending_idx')
      .on(t.status)
      .where(sql`${t.status} = 'PENDING'`),
  ],
);
